# Generated by Django 4.1.2 on 2023-04-19 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaC',
            fields=[
                ('idFacturaC', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cantProduct', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('nombreProveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaV',
            fields=[
                ('idFacturaV', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cantProduct', models.IntegerField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('nombreCliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidadProducto', models.IntegerField()),
                ('precioUnit', models.IntegerField()),
                ('foto', models.ImageField(upload_to='lati/images/')),
                ('peso', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
