# Generated by Django 4.0 on 2023-04-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaC',
            fields=[
                ('idFacturaC', models.IntegerField(primary_key=True, serialize=False)),
                ('cantProduct', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('fecha', models.CharField(max_length=20)),
                ('nombreProveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaV',
            fields=[
                ('idFacturaV', models.IntegerField(primary_key=True, serialize=False)),
                ('cantProduct', models.IntegerField()),
                ('totall', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('debe', models.BooleanField(default=False, null=True)),
                ('cuanto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidadProducto', models.IntegerField()),
                ('precioUnit', models.IntegerField()),
                ('foto', models.ImageField(upload_to='lati/images/')),
                ('peso', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
