# Generated by Django 4.1.2 on 2023-05-15 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidadProducto', models.PositiveIntegerField()),
                ('precioUnit', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='lati/images/')),
                ('peso', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaV',
            fields=[
                ('idFacturaV', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cantProduct', models.PositiveIntegerField()),
                ('totall', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('debe', models.BooleanField(default=False, null=True)),
                ('cuanto', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaC',
            fields=[
                ('idFacturaC', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cantProduct', models.PositiveIntegerField()),
                ('costo', models.PositiveIntegerField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nombreProveedor', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
