# Generated by Django 4.1.6 on 2023-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturav',
            name='cuanto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturav',
            name='debe',
            field=models.BooleanField(default=False),
        ),
    ]
