# Generated by Django 4.1.2 on 2023-04-14 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoriaP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lati.categoria'),
        ),
    ]
