# Generated by Django 4.1.6 on 2023-05-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturav',
            old_name='cantProduct',
            new_name='cantProduct1',
        ),
    ]
