# Generated by Django 4.1.2 on 2023-04-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0002_alter_producto_categoriap'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaV',
            fields=[
                ('idFacturaV', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cantProduct', models.IntegerField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lati.producto')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaC',
            fields=[
                ('idFacturaC', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cantProduct', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('nombreProveedor', models.CharField(max_length=50)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lati.producto')),
            ],
        ),
    ]
