# Generated by Django 4.1.2 on 2023-04-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0002_facturac_user_facturav_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturac',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facturav',
            name='user',
        ),
    ]
