# Generated by Django 4.1.6 on 2023-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0002_facturav_cuanto_facturav_debe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturav',
            name='cuanto',
            field=models.IntegerField(null=True),
        ),
    ]
