# Generated by Django 4.0 on 2023-05-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0003_alter_facturac_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturac',
            name='fecha',
            field=models.DateField(),
        ),
    ]
