# Generated by Django 4.0 on 2023-05-09 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0004_alter_facturac_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturav',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='facturac',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
