# Generated by Django 4.1.2 on 2023-05-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0004_facturac_user_facturav_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturac',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facturav',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
        migrations.AddField(
            model_name='producto',
            name='images',
            field=models.ImageField(default=0, upload_to='media/lati/images/'),
            preserve_default=False,
        ),
    ]
