# Generated by Django 4.1.2 on 2023-04-14 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lati', '0004_facturac_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturac',
            name='user',
        ),
        migrations.AddField(
            model_name='producto',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
