# Generated by Django 4.1.6 on 2023-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0005_facturav_fecha_alter_facturac_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='media/lati/images/'),
        ),
    ]
