# Generated by Django 4.1.2 on 2023-04-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0005_remove_facturac_user_producto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='lati/images/'),
        ),
    ]
