# Generated by Django 4.1.2 on 2023-04-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0006_alter_producto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
