# Generated by Django 4.1.6 on 2023-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0006_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidadProducto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioUnit',
            field=models.PositiveIntegerField(),
        ),
    ]
