# Generated by Django 4.1.2 on 2023-04-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0007_remove_producto_idproducto_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(default=1, max_length=25, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
