# Generated by Django 4.1.2 on 2023-04-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0009_alter_producto_idproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturac',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='facturav',
            name='productos',
        ),
    ]
