# Generated by Django 4.1.2 on 2023-04-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0011_categoria_user_alter_categoria_idcategoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturaC',
        ),
    ]
