# Generated by Django 4.1.2 on 2023-04-15 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lati', '0013_auto_20230414_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaC',
            fields=[
                ('idFacturaC', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cantProduct', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('nombreProveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
