# Generated by Django 4.1.2 on 2023-04-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0015_remove_producto_categoriap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
