# Generated by Django 4.1.2 on 2023-04-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lati', '0016_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=50)),
            ],
        ),
    ]
